### ISSUE TITLE
Allow use of arrow `operator->` on return value of `huffman::table::find`

### ISSUE THREAD

**Issue by garymm** [garymm/gpu-deflate#49]
Minimal reproducer of what I think is the issue: https://godbolt.org/z/3sEq5z4ro
ChatGPT's opinion:
https://chat.openai.com/share/b99fc143-1870-4f94-b604-2fd4c56e9c49

**Comment by oliverlee** [comment]
See this:
https://stackoverflow.com/questions/67063300/c-ranges-view-iterators-and-operator
and this:
https://quuxplusone.github.io/blog/2019/02/06/arrow-proxy/

It looks like `transform_view` doesn't implement `operator->`:
https://en.cppreference.com/w/cpp/ranges/transform_view/iterator
